### ISSUE TITLE
Add ecommerce related layouts.

### ISSUE THREAD

**Issue by kaspar-naaber** [Voog/design-longyearbyen#78]
(Pull request: #79) (merged)
(Pull request: #102)

How it works: http://recordit.co/RcEQtQAsAg

# Task list

- [x] Product list
- [x] Product

## Detailed task list

- [x] Migrate base code from https://github.com/Voog/design-sapporo
- [x] Cleanup code.
- [x] Add second level menu for products listing view.
- [x] Add option to toggle categories from main menu if Front page is products list.
- [x] Hide products related layouts from sub menu.
- [x] Hide products related layouts from mobile menu.

**Comment by SSirjes** [comment]
* [ ] product layout. Product picture is out of proportion

![screen shot 2017-01-05 at 09 04 18](https://cloud.githubusercontent.com/assets/13623224/21671717/fa155258-d325-11e6-9f08-52a8b5442ea4.png)

**Comment by SSirjes** [comment]
* [ ] Product layout is not displayed in main menu

**Comment by kaspar-naaber** [comment]
- [ ] List non-product related pages in submenu.

**Comment by kaspar-naaber** [comment]
## Additional tasks for "Product" layout.
- [ ] Add specific placeholder for "drag product here".
- [ ] Convert description area to `{% contentblock %}` with description.

**Comment by SSirjes** [comment]
* [ ] Should product list layout have two '+ add subpage' button?

* If I create new subpage,with first '+ add subpage' button, then menu item jumps under product list submenu --> look the video, what happens: http://recordit.co/yefkk1H47r

**Comment by SSirjes** [comment]
* [ ] Product layouts should have breadcrumbs

**Comment by SSirjes** [comment]
* [ ] If root layout is 'Product', then 'Settings' - 'Show in main menu' button function don't work
_Video, how it works at the moment: http://recordit.co/0VIbRHCWeA_

**Comment by SSirjes** [comment]
* [ ] Should 'Product' layout display 'Untranslated' menu item button? 

![screen_shot_2017-01-10_at_12_59_30](https://cloud.githubusercontent.com/assets/13623224/21804299/ecda4f02-d736-11e6-82db-ff54cf4173ab.png)
